### ISSUE TITLE
Error running migrate-postgres

### ISSUE THREAD

**Issue by Kiran-Crawford** [ben-willis/grey-jcr#45]
I reset docker again but haven't been able to complete running docker-compose run migrate-postgres, it gets through all of building everything then I get this:
```
> grey-jcr@2.0.0 migrate-postgres /usr/app
> knex migrate:latest

Error: connect ECONNREFUSED 92.242.132.16:5432
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1105:14)

npm ERR! Linux 4.9.87-linuxkit-aufs
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "migrate-postgres"
npm ERR! node v6.13.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! grey-jcr@2.0.0 migrate-postgres: `knex migrate:latest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grey-jcr@2.0.0 migrate-postgres script 'knex migrate:latest'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grey-jcr package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     knex migrate:latest
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grey-jcr
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grey-jcr
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/app/npm-debug.log
```

**Comment by ben-willis** [comment]
I've seen this before, seems to be related to this:
https://github.com/docker/compose/issues/3492

Solution is to run `docker compose up -d` before running the migrate command. Will update the readme.

**Comment by ben-willis** [comment]
I think a long term solution would be better, have suggested a possible solution here #48

**Comment by Kiran-Crawford** [comment]
If I run docker-compose up -d first I still get an error, it gets through a lot of stuff but then at the end says the container is unhealthy, I've reset docker to factory defaults again and still get it - Don't know if I've managed to permanently mess something up so bad or something in the recent code changes has stopped it from working on my computer
```
...
Step 11/11 : CMD npm run start
 ---> Running in b848d1f6c1c9
Removing intermediate container b848d1f6c1c9
 ---> 314ec68317a0
Successfully built 314ec68317a0
Successfully tagged greyjcr/app:latest
WARNING: Image for service app was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating greyjcr_redis_1    ... done
Creating greyjcr_postgres_1 ... done

ERROR: for app  Container "c783ec599230" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

The error I posted yesterday turns out to be something to do with talktalk hijacking dns error pages to give their own custom errors, on different wifi the error when running migrate-postgres (before or after docker compose up) turns out to be this, looks to be soemthing worng with connecting to postgres on port 5432
```
D:\kiran\Grey2\grey-jcr>docker-compose run app npm run migrate-postgres
Starting greyjcr_redis_1    ... done
Starting greyjcr_postgres_1 ... done

> grey-jcr@2.0.0 migrate-postgres /usr/app
> knex migrate:latest

Error: getaddrinfo ENOTFOUND postgres postgres:5432
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

npm ERR! Linux 4.9.87-linuxkit-aufs
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "migrate-postgres"
npm ERR! node v6.13.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! grey-jcr@2.0.0 migrate-postgres: `knex migrate:latest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grey-jcr@2.0.0 migrate-postgres script 'knex migrate:latest'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grey-jcr package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     knex migrate:latest
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grey-jcr
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grey-jcr
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/app/npm-debug.log
```

**Comment by Kiran-Crawford** [comment]
I tried using some older versions that definitely used to work and they don't anymore so I've messed something up - I'll try reinstalling docker sometime to see if that helps

**Comment by ben-willis** [comment]
Hmmm I must admit I haven't tested this on Windows. I will try and reproduce it locally. Are you using Docker for Windows (on Windows 10 Pro) or Docker Toolkit (on Windows 10 Home)?

**Comment by Kiran-Crawford** [comment]
I'm using docker for Windows on windows 10 pro

**Comment by ben-willis** [comment]
Ah I don't have Windows 10 Pro so I can't install Docker for Windows. I would suggest re-cloning the repository if you haven't done so already and starting from a clean slate.

If you get the "container is unhealthy" error again try checking the logs (`docker-compose logs`) to see if there are any clues in there. I would recommend running `docker-compose up -d` before any of the `docker-compose run` commands just to make sure all the aliases are set. You'll also need to make sure you're sharing the drive: https://rominirani.com/docker-on-windows-mounting-host-directories-d96f3f056a2c

 This might be tricky to debug given that I can't reproduce it but I'll keep thinking of ideas.

**Comment by ben-willis** [comment]
Moved away from Docker so hopefully a bit more Windows friendly. Closing this issue.
