### ISSUE TITLE
Website performance

### ISSUE THREAD

**Issue by d-nagy** [ben-willis/grey-jcr#55]
During the largest booking events, the website struggles - i.e. becomes very very slow (unacceptably slow) - even on very overpowered hardware. 

I wonder if it its worth implementing Node.js clustering? Something like PM2 seems perhaps doable: 
http://pm2.keymetrics.io/docs/usage/docker-pm2-nodejs/

This is just my two cents, but I think this may help since it appears the application is not utilising all CPU cores that are available - at least, it certainly hasn't used the 24 cores available to it in the Phoenix Ball bookings...

It would be good to get your thoughts on this.

**Comment by ben-willis** [comment]
You're definitely right about the website not making the most of the available hardware. I don't know much about Node.js clustering but it looks interesting and relatively simple to set up. If you want to experiment with this locally I think it could be well worth it.

I guess an alternative would be to ditch docker and just run the app directly on the server as we were doing before. I was hoping it would make development easier but perhaps it caused more harm than good. It's definitely open for discussion!

**Comment by d-nagy** [comment]
I'lll have a go at clustering locally. To be honest, I think docker has been a good change overall, we just need to figure everything out. Speaking of which, the docker container timezone is incorrect. I have a fix which I'll make a pull request for and you can have a look.

**Comment by d-nagy** [comment]
PR #70 intended be an initial solution to this problem, and as far as I can tell, has been successful. Node now forks off a worker process for every available CPU, so in theory the performance should be improved. 

Until there is an event booking large enough to properly confirm this, I'm going to consider this issue resolved.
