### ISSUE TITLE
Timezone incorrect on container

### ISSUE THREAD

**Issue by d-nagy** [ben-willis/grey-jcr#60]
We believed that the changes in pull request #58 would cause the timezone to be set correctly on the docker container, but alas it seems that hasn't worked on the production server, despite working fine on my local version at least. It's not a particularly urgent problem, but it is pretty annoying when setting booking times and such and it would be great to figure something out.

It would be interesting to know whether it works on your local versions too, or if I just got lucky.

**Comment by ben-willis** [comment]
It looks like it's working on my local version to me? It also looks like it's working in prod as well?

When I created a test ticket and set the booking time to open in two hours the countdown was corect. Is there any other way I can test this?

**Comment by d-nagy** [comment]
Oh, that's good news then - I was testing by using the ```docker exec -it <container_id> date``` command. I must admit I did not test making a ticket. If it has worked for that then that's fine.

**Comment by d-nagy** [comment]
I'm happy to close this then if it everything is ok after all.

**Comment by ben-willis** [comment]
Hmm using that command worked for me. Maybe your fix hadn't been implemented? I'll close this...
