### ISSUE TITLE
Development pipeline redesign

### ISSUE THREAD

**Issue by ben-willis** [ben-willis/grey-jcr#68]
A place to discuss the current use of docker and the option of a pipeline redesign.

Currently we build docker image locally gor the grey jcr app. We then use docker compose to manage the dependencies on postgres and redis. Issues with this approach:
- Possible overcomplicated CI pipeline
- Issues with running Docker on Windows (@Kiran-Crawford)
- Maybe performance issues?

**Comment by ben-willis** [comment]
> I'm not gonna lie, I found it great to be honest (maybe I've gotten lucky).
So far I've been running it on Debian and its worked fine. I found it makes
installation easier just because it handles postgresql. I've not tried it
on Windows though before, so I can't comment on that side of it. I also
haven't really noticed performance issues, but that also could easily be me
being oblivious to things.

> I would be interested to know the kinds of issues we are having though with
it. I may try my hand at getting it working on Windows and see what happens.

@d-nagy

**Comment by ben-willis** [comment]
It sounds like the most important requirement is being able to run the app easily locally for development and managing the dependencies on other services.

An alternative approach would be to be to provide a VM that has postgres/node/redis preinstalled and provide this to developers? This VM would mirror the production server.

My main issue with Docker is that it's useful if your application consists of multiple services that can be distributed. However the current app runs as a single monolith. I'm also worried running Postgres in a docker container is bad practice.

**Comment by d-nagy** [comment]
So do you mean something like using Virtualbox and its ability to export an "appliance"? That might be alright actually, as long as we do a really good job of setting it up. It would be worth a try at least to compare to Docker currently.

**Comment by ben-willis** [comment]
Yeah that would be an option.

Another option would be only using docker for development and then deploying natively on the prod server. We lose some of the niceness of docker running everywhere though...
